# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_elements\ChannelSelectionPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_channel_selection_dialog(object):
    def setupUi(self, channel_selection_dialog):
        channel_selection_dialog.setObjectName("channel_selection_dialog")
        channel_selection_dialog.resize(470, 395)
        self.horizontalLayoutWidget = QtWidgets.QWidget(channel_selection_dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 340, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.channel_selection_accept_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.channel_selection_accept_button.setObjectName("channel_selection_accept_button")
        self.horizontalLayout.addWidget(self.channel_selection_accept_button)
        self.channel_selection_cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.channel_selection_cancel_button.setObjectName("channel_selection_cancel_button")
        self.horizontalLayout.addWidget(self.channel_selection_cancel_button)
        self.channel_list_view = QtWidgets.QListWidget(channel_selection_dialog)
        self.channel_list_view.setGeometry(QtCore.QRect(20, 10, 431, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_list_view.sizePolicy().hasHeightForWidth())
        self.channel_list_view.setSizePolicy(sizePolicy)
        self.channel_list_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.channel_list_view.setObjectName("channel_list_view")

        self.retranslateUi(channel_selection_dialog)
        QtCore.QMetaObject.connectSlotsByName(channel_selection_dialog)

    def retranslateUi(self, channel_selection_dialog):
        _translate = QtCore.QCoreApplication.translate
        channel_selection_dialog.setWindowTitle(_translate("channel_selection_dialog", "Dialog"))
        self.channel_selection_accept_button.setText(_translate("channel_selection_dialog", "Aceptar"))
        self.channel_selection_cancel_button.setText(_translate("channel_selection_dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    channel_selection_dialog = QtWidgets.QDialog()
    ui = Ui_channel_selection_dialog()
    ui.setupUi(channel_selection_dialog)
    channel_selection_dialog.show()
    sys.exit(app.exec_())
